#!/usr/bin/env bash

date=$(date '+%Y/%m/%d')
filename="diary/$date.md"

if [ ! -f $filename ]
then
    cp "${PWD}/scripts/template.md" $filename
    vim $filename
else
    echo "File already exists"
fi
