name: Deploy to Firebase Hosting on merge
'on':
  pull_request_review:
    types: [submitted]

jobs:
  build_and_deploy:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHABLO }}'
          channelId: live
          projectId: chablo
